<?php

use Illuminate\Database\Seeder;
use App\Familia;
use Illuminate\Support\Str;
class FamiliaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        //factory(Familia::class)->times(10)->create();        
Familia::create(['id'=>1010,'detfamilia'=>'Animales vivos','slug'=>Str::slug('Animales vivos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1011,'detfamilia'=>'Productos para animales domésticos','slug'=>Str::slug('Productos para animales domésticos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1012,'detfamilia'=>'Comida de animales','slug'=>Str::slug('Comida de animales','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1013,'detfamilia'=>'Recipientes y hábitat para animales','slug'=>Str::slug('Recipientes y hábitat para animales','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1014,'detfamilia'=>'Productos de talabartería y arreo','slug'=>Str::slug('Productos de talabartería y arreo','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1015,'detfamilia'=>'Semillas, bulbos, plántulas y esquejes','slug'=>Str::slug('Semillas, bulbos, plántulas y esquejes','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1016,'detfamilia'=>'Productos de floricultura y silvicultura','slug'=>Str::slug('Productos de floricultura y silvicultura','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1017,'detfamilia'=>'Fertilizantes y nutrientes para plantas y herbicidas','slug'=>Str::slug('Fertilizantes y nutrientes para plantas y herbicidas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1019,'detfamilia'=>'Productos para el control de plagas ','slug'=>Str::slug('Productos para el control de plagas ','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1020,'detfamilia'=>'Rosales vivos','slug'=>Str::slug('Rosales vivos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1021,'detfamilia'=>'Plantas vivas  de especies o variedades de flores altas','slug'=>Str::slug('Plantas vivas  de especies o variedades de flores altas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1022,'detfamilia'=>'Plantas vivas  de especies o variedades de flores bajas','slug'=>Str::slug('Plantas vivas  de especies o variedades de flores bajas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1023,'detfamilia'=>'Crisantemos vivos','slug'=>Str::slug('Crisantemos vivos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1024,'detfamilia'=>'Claveles vivos','slug'=>Str::slug('Claveles vivos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1025,'detfamilia'=>'Orquídeas vivas','slug'=>Str::slug('Orquídeas vivas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1030,'detfamilia'=>'Rosas frescas cortadas','slug'=>Str::slug('Rosas frescas cortadas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1031,'detfamilia'=>'Bouquets cortados frescos  de especies o variedades de flores altas','slug'=>Str::slug('Bouquets cortados frescos  de especies o variedades de flores altas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1032,'detfamilia'=>'Bouquets cortados frescos  de especies o variedades de flores bajas','slug'=>Str::slug('Bouquets cortados frescos  de especies o variedades de flores bajas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1033,'detfamilia'=>'Crisantemos cortados frescos','slug'=>Str::slug('Crisantemos cortados frescos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1034,'detfamilia'=>'Bouquets florales cortados frescos','slug'=>Str::slug('Bouquets florales cortados frescos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1035,'detfamilia'=>'Claveles cortados frescos','slug'=>Str::slug('Claveles cortados frescos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1036,'detfamilia'=>'Orquídeas cortadas frescas','slug'=>Str::slug('Orquídeas cortadas frescas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1040,'detfamilia'=>'Rosas cortadas secas','slug'=>Str::slug('Rosas cortadas secas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1041,'detfamilia'=>'Bouquets cortados secos  de especies o variedades de flores altas','slug'=>Str::slug('Bouquets cortados secos  de especies o variedades de flores altas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1042,'detfamilia'=>'Bouquets cortados secos  de especies o variedades de flores bajas','slug'=>Str::slug('Bouquets cortados secos  de especies o variedades de flores bajas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1043,'detfamilia'=>'Crisantemos cortados secos','slug'=>Str::slug('Crisantemos cortados secos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1044,'detfamilia'=>'Claveles cortados secos','slug'=>Str::slug('Claveles cortados secos','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1045,'detfamilia'=>'Orquídeas cortadas secas','slug'=>Str::slug('Orquídeas cortadas secas','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1050,'detfamilia'=>'Follaje cortado fresco','slug'=>Str::slug('Follaje cortado fresco','-'),'segmento_id'=>'10',]);
Familia::create(['id'=>1110,'detfamilia'=>'Minerales, minerales metálicos y metales','slug'=>Str::slug('Minerales, minerales metálicos y metales','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1111,'detfamilia'=>'Tierra y piedra','slug'=>Str::slug('Tierra y piedra','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1112,'detfamilia'=>'Productos no comestibles de planta y silvicultura','slug'=>Str::slug('Productos no comestibles de planta y silvicultura','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1113,'detfamilia'=>'Productos animales no comestibles','slug'=>Str::slug('Productos animales no comestibles','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1114,'detfamilia'=>'Chatarra y materiales de desecho','slug'=>Str::slug('Chatarra y materiales de desecho','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1115,'detfamilia'=>'Fibra, hilos e hilados','slug'=>Str::slug('Fibra, hilos e hilados','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1116,'detfamilia'=>'Tejidos y materiales de cuero','slug'=>Str::slug('Tejidos y materiales de cuero','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1117,'detfamilia'=>'Aleaciones','slug'=>Str::slug('Aleaciones','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1118,'detfamilia'=>'Óxido metálico','slug'=>Str::slug('Óxido metálico','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1119,'detfamilia'=>'Desechos metálicos y chatarra','slug'=>Str::slug('Desechos metálicos y chatarra','-'),'segmento_id'=>'11',]);
Familia::create(['id'=>1213,'detfamilia'=>'Materiales explosivos','slug'=>Str::slug('Materiales explosivos','-'),'segmento_id'=>'12',]);
Familia::create(['id'=>1214,'detfamilia'=>'Elementos y gases','slug'=>Str::slug('Elementos y gases','-'),'segmento_id'=>'12',]);
Familia::create(['id'=>1216,'detfamilia'=>'Aditivos','slug'=>Str::slug('Aditivos','-'),'segmento_id'=>'12',]);
Familia::create(['id'=>1217,'detfamilia'=>'Colorantes','slug'=>Str::slug('Colorantes','-'),'segmento_id'=>'12',]);
Familia::create(['id'=>1218,'detfamilia'=>'Ceras y aceites','slug'=>Str::slug('Ceras y aceites','-'),'segmento_id'=>'12',]);
Familia::create(['id'=>1219,'detfamilia'=>'Solventes','slug'=>Str::slug('Solventes','-'),'segmento_id'=>'12',]);
Familia::create(['id'=>1235,'detfamilia'=>'Compuestos y mezclas','slug'=>Str::slug('Compuestos y mezclas','-'),'segmento_id'=>'12',]);
Familia::create(['id'=>1310,'detfamilia'=>'Caucho y elastómeros','slug'=>Str::slug('Caucho y elastómeros','-'),'segmento_id'=>'13',]);
Familia::create(['id'=>1311,'detfamilia'=>'Resinas y colofonias y otros materiales derivados de resina','slug'=>Str::slug('Resinas y colofonias y otros materiales derivados de resina','-'),'segmento_id'=>'13',]);
Familia::create(['id'=>1410,'detfamilia'=>'Materiales de papel','slug'=>Str::slug('Materiales de papel','-'),'segmento_id'=>'14',]);
Familia::create(['id'=>1411,'detfamilia'=>'Productos de papel','slug'=>Str::slug('Productos de papel','-'),'segmento_id'=>'14',]);
Familia::create(['id'=>1412,'detfamilia'=>'Papel para uso industrial','slug'=>Str::slug('Papel para uso industrial','-'),'segmento_id'=>'14',]);
Familia::create(['id'=>1510,'detfamilia'=>'Combustibles','slug'=>Str::slug('Combustibles','-'),'segmento_id'=>'15',]);
Familia::create(['id'=>1511,'detfamilia'=>'Combustibles gaseosos y aditivos','slug'=>Str::slug('Combustibles gaseosos y aditivos','-'),'segmento_id'=>'15',]);
Familia::create(['id'=>1512,'detfamilia'=>'Lubricantes, aceites, grasas y anticorrosivos','slug'=>Str::slug('Lubricantes, aceites, grasas y anticorrosivos','-'),'segmento_id'=>'15',]);
Familia::create(['id'=>1513,'detfamilia'=>'Combustible para reactores nucleares','slug'=>Str::slug('Combustible para reactores nucleares','-'),'segmento_id'=>'15',]);
Familia::create(['id'=>2010,'detfamilia'=>'Maquinaria y equipo de minería y explotación de canteras','slug'=>Str::slug('Maquinaria y equipo de minería y explotación de canteras','-'),'segmento_id'=>'20',]);
Familia::create(['id'=>2011,'detfamilia'=>'Equipo de perforación y explotación de pozos','slug'=>Str::slug('Equipo de perforación y explotación de pozos','-'),'segmento_id'=>'20',]);
Familia::create(['id'=>2012,'detfamilia'=>'Equipo para perforación y exploración de petróleo y gas','slug'=>Str::slug('Equipo para perforación y exploración de petróleo y gas','-'),'segmento_id'=>'20',]);
Familia::create(['id'=>2013,'detfamilia'=>'Materiales para  perforación y operaciones de petróleo y gas','slug'=>Str::slug('Materiales para  perforación y operaciones de petróleo y gas','-'),'segmento_id'=>'20',]);
Familia::create(['id'=>2014,'detfamilia'=>'Equipo de producción y operación de petróleo y gas','slug'=>Str::slug('Equipo de producción y operación de petróleo y gas','-'),'segmento_id'=>'20',]);
Familia::create(['id'=>2110,'detfamilia'=>'Maquinaria y equipo para agricultura, silvicultura y paisajismo','slug'=>Str::slug('Maquinaria y equipo para agricultura, silvicultura y paisajismo','-'),'segmento_id'=>'21',]);
Familia::create(['id'=>2111,'detfamilia'=>'Equipo de pesca y acuicultura','slug'=>Str::slug('Equipo de pesca y acuicultura','-'),'segmento_id'=>'21',]);
Familia::create(['id'=>2210,'detfamilia'=>'Maquinaria y equipo pesado de construcción','slug'=>Str::slug('Maquinaria y equipo pesado de construcción','-'),'segmento_id'=>'22',]);
Familia::create(['id'=>2310,'detfamilia'=>'Maquinaria para el procesamiento de materias primas','slug'=>Str::slug('Maquinaria para el procesamiento de materias primas','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2311,'detfamilia'=>'Maquinaria para el procesamiento de petróleo','slug'=>Str::slug('Maquinaria para el procesamiento de petróleo','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2312,'detfamilia'=>'Maquinaria y accesorios de textiles y tejidos','slug'=>Str::slug('Maquinaria y accesorios de textiles y tejidos','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2313,'detfamilia'=>'Maquinaria y equipos lapidarios','slug'=>Str::slug('Maquinaria y equipos lapidarios','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2314,'detfamilia'=>'Maquinaria de reparación y accesorios para marroquinería','slug'=>Str::slug('Maquinaria de reparación y accesorios para marroquinería','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2315,'detfamilia'=>'Maquinaria, equipo y suministros de procesos industriales','slug'=>Str::slug('Maquinaria, equipo y suministros de procesos industriales','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2316,'detfamilia'=>'Máquinas, equipo y suministros para fundición','slug'=>Str::slug('Máquinas, equipo y suministros para fundición','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2318,'detfamilia'=>'Equipo industrial para alimentos y bebidas','slug'=>Str::slug('Equipo industrial para alimentos y bebidas','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2319,'detfamilia'=>'Mezcladores y sus partes y accesorios','slug'=>Str::slug('Mezcladores y sus partes y accesorios','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2320,'detfamilia'=>'Equipamiento para transferencia de masa','slug'=>Str::slug('Equipamiento para transferencia de masa','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2321,'detfamilia'=>'Maquinaria de fabricación electrónica, equipo y accesorios','slug'=>Str::slug('Maquinaria de fabricación electrónica, equipo y accesorios','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2322,'detfamilia'=>'Equipo y maquinaria de procesamiento de pollos','slug'=>Str::slug('Equipo y maquinaria de procesamiento de pollos','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2323,'detfamilia'=>'Equipo y maquinaria de procesamiento de madera y aserrado','slug'=>Str::slug('Equipo y maquinaria de procesamiento de madera y aserrado','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2324,'detfamilia'=>'Maquinaria y accesorios para cortar metales','slug'=>Str::slug('Maquinaria y accesorios para cortar metales','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2325,'detfamilia'=>'Maquinaria y accesorios para el formado de metales','slug'=>Str::slug('Maquinaria y accesorios para el formado de metales','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2326,'detfamilia'=>'Maquinaria y accesorios para hacer prototipos rápidos','slug'=>Str::slug('Maquinaria y accesorios para hacer prototipos rápidos','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2327,'detfamilia'=>'Maquinaria y accesorios y suministros para soldadura de todas las clases','slug'=>Str::slug('Maquinaria y accesorios y suministros para soldadura de todas las clases','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2328,'detfamilia'=>'Maquinaria para el tratamiento de metal','slug'=>Str::slug('Maquinaria para el tratamiento de metal','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2329,'detfamilia'=>'Herramientas de maquinado industrial','slug'=>Str::slug('Herramientas de maquinado industrial','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2330,'detfamilia'=>'Maquinaria y equipo para cable','slug'=>Str::slug('Maquinaria y equipo para cable','-'),'segmento_id'=>'23',]);
Familia::create(['id'=>2410,'detfamilia'=>'Maquinaria y equipo para manejo de materiales','slug'=>Str::slug('Maquinaria y equipo para manejo de materiales','-'),'segmento_id'=>'24',]);
Familia::create(['id'=>2411,'detfamilia'=>'Recipientes y almacenamiento','slug'=>Str::slug('Recipientes y almacenamiento','-'),'segmento_id'=>'24',]);
Familia::create(['id'=>2412,'detfamilia'=>'Materiales de empaque','slug'=>Str::slug('Materiales de empaque','-'),'segmento_id'=>'24',]);
Familia::create(['id'=>2413,'detfamilia'=>'Refrigeración industrial','slug'=>Str::slug('Refrigeración industrial','-'),'segmento_id'=>'24',]);
Familia::create(['id'=>2414,'detfamilia'=>'Suministros de embalaje','slug'=>Str::slug('Suministros de embalaje','-'),'segmento_id'=>'24',]);
Familia::create(['id'=>2510,'detfamilia'=>'Vehículos de motor','slug'=>Str::slug('Vehículos de motor','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2511,'detfamilia'=>'Transporte marítimo','slug'=>Str::slug('Transporte marítimo','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2512,'detfamilia'=>'Maquinaria y equipo para ferrocarril y tranvías','slug'=>Str::slug('Maquinaria y equipo para ferrocarril y tranvías','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2513,'detfamilia'=>'Aeronaves','slug'=>Str::slug('Aeronaves','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2515,'detfamilia'=>'Naves espaciales','slug'=>Str::slug('Naves espaciales','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2516,'detfamilia'=>'Bicicletas no motorizadas','slug'=>Str::slug('Bicicletas no motorizadas','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2517,'detfamilia'=>'Componentes y sistemas de transporte','slug'=>Str::slug('Componentes y sistemas de transporte','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2518,'detfamilia'=>'Carrocerías y remolques','slug'=>Str::slug('Carrocerías y remolques','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2519,'detfamilia'=>'Equipo para servicios de transporte','slug'=>Str::slug('Equipo para servicios de transporte','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2520,'detfamilia'=>'Sistemas  y componentes y equipos aeroespaciales','slug'=>Str::slug('Sistemas  y componentes y equipos aeroespaciales','-'),'segmento_id'=>'25',]);
Familia::create(['id'=>2610,'detfamilia'=>'Fuentes de energía','slug'=>Str::slug('Fuentes de energía','-'),'segmento_id'=>'26',]);
Familia::create(['id'=>2611,'detfamilia'=>'Baterías y generadores y transmisión de energía cinética','slug'=>Str::slug('Baterías y generadores y transmisión de energía cinética','-'),'segmento_id'=>'26',]);
Familia::create(['id'=>2612,'detfamilia'=>'Alambres, cables y arneses','slug'=>Str::slug('Alambres, cables y arneses','-'),'segmento_id'=>'26',]);
Familia::create(['id'=>2613,'detfamilia'=>'Generación de energía','slug'=>Str::slug('Generación de energía','-'),'segmento_id'=>'26',]);
Familia::create(['id'=>2614,'detfamilia'=>'Maquinaria y equipo para energía atómica o nuclear','slug'=>Str::slug('Maquinaria y equipo para energía atómica o nuclear','-'),'segmento_id'=>'26',]);
Familia::create(['id'=>2711,'detfamilia'=>'Herramientas de mano','slug'=>Str::slug('Herramientas de mano','-'),'segmento_id'=>'27',]);
Familia::create(['id'=>2712,'detfamilia'=>'Maquinaria y equipo hidráulico','slug'=>Str::slug('Maquinaria y equipo hidráulico','-'),'segmento_id'=>'27',]);
Familia::create(['id'=>2713,'detfamilia'=>'Maquinaria y equipo neumático','slug'=>Str::slug('Maquinaria y equipo neumático','-'),'segmento_id'=>'27',]);
Familia::create(['id'=>2714,'detfamilia'=>'Herramientas especializadas automotrices','slug'=>Str::slug('Herramientas especializadas automotrices','-'),'segmento_id'=>'27',]);
Familia::create(['id'=>3010,'detfamilia'=>'Componentes estructurales y formas básicas','slug'=>Str::slug('Componentes estructurales y formas básicas','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3011,'detfamilia'=>'Hormigón, cemento y yeso','slug'=>Str::slug('Hormigón, cemento y yeso','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3012,'detfamilia'=>'Carreteras y paisaje','slug'=>Str::slug('Carreteras y paisaje','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3013,'detfamilia'=>'Productos de construcción estructurales','slug'=>Str::slug('Productos de construcción estructurales','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3014,'detfamilia'=>'Aislamiento','slug'=>Str::slug('Aislamiento','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3015,'detfamilia'=>'Materiales para acabado de exteriores','slug'=>Str::slug('Materiales para acabado de exteriores','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3016,'detfamilia'=>'Materiales de acabado de interiores','slug'=>Str::slug('Materiales de acabado de interiores','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3017,'detfamilia'=>'Puertas y ventanas y vidrio','slug'=>Str::slug('Puertas y ventanas y vidrio','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3018,'detfamilia'=>'Instalaciones de plomería','slug'=>Str::slug('Instalaciones de plomería','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3019,'detfamilia'=>'Equipo de apoyo para Construcción y Mantenimiento','slug'=>Str::slug('Equipo de apoyo para Construcción y Mantenimiento','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3024,'detfamilia'=>'Componentes de construcción de estructura portátil','slug'=>Str::slug('Componentes de construcción de estructura portátil','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3025,'detfamilia'=>'Estructuras y materiales de minería subterránea','slug'=>Str::slug('Estructuras y materiales de minería subterránea','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3026,'detfamilia'=>'Materiales estructurales','slug'=>Str::slug('Materiales estructurales','-'),'segmento_id'=>'30',]);
Familia::create(['id'=>3110,'detfamilia'=>'Piezas de fundición y ensambles de piezas de fundición','slug'=>Str::slug('Piezas de fundición y ensambles de piezas de fundición','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3111,'detfamilia'=>'Extrusiones','slug'=>Str::slug('Extrusiones','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3112,'detfamilia'=>'Piezas fundidas maquinadas','slug'=>Str::slug('Piezas fundidas maquinadas','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3113,'detfamilia'=>'Forjaduras','slug'=>Str::slug('Forjaduras','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3114,'detfamilia'=>'Molduras','slug'=>Str::slug('Molduras','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3115,'detfamilia'=>'Cuerda, cadena, cable, alambre y correa','slug'=>Str::slug('Cuerda, cadena, cable, alambre y correa','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3116,'detfamilia'=>'Ferretería','slug'=>Str::slug('Ferretería','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3117,'detfamilia'=>'Rodamientos, cojinetes ruedas y engranajes','slug'=>Str::slug('Rodamientos, cojinetes ruedas y engranajes','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3118,'detfamilia'=>'Empaques, glándulas, fundas y cubiertas','slug'=>Str::slug('Empaques, glándulas, fundas y cubiertas','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3119,'detfamilia'=>'Materiales de afilado pulido y alisado','slug'=>Str::slug('Materiales de afilado pulido y alisado','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3120,'detfamilia'=>'Adhesivos y selladores','slug'=>Str::slug('Adhesivos y selladores','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3121,'detfamilia'=>'Pinturas y bases y acabados','slug'=>Str::slug('Pinturas y bases y acabados','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3122,'detfamilia'=>'Extractos de teñir y de curtir','slug'=>Str::slug('Extractos de teñir y de curtir','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3123,'detfamilia'=>'Materia prima en placas o barras labradas','slug'=>Str::slug('Materia prima en placas o barras labradas','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3124,'detfamilia'=>'Óptica industrial','slug'=>Str::slug('Óptica industrial','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3125,'detfamilia'=>'Sistemas de control neumático, hidráulico o eléctrico','slug'=>Str::slug('Sistemas de control neumático, hidráulico o eléctrico','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3126,'detfamilia'=>'Cubiertas, cajas y envolturas','slug'=>Str::slug('Cubiertas, cajas y envolturas','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3127,'detfamilia'=>'Piezas hechas a máquina','slug'=>Str::slug('Piezas hechas a máquina','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3128,'detfamilia'=>'Componentes de placa y estampados','slug'=>Str::slug('Componentes de placa y estampados','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3129,'detfamilia'=>'Extrusiones maquinadas','slug'=>Str::slug('Extrusiones maquinadas','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3130,'detfamilia'=>'Forjas labradas','slug'=>Str::slug('Forjas labradas','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3131,'detfamilia'=>'Ensambles de tubería fabricada','slug'=>Str::slug('Ensambles de tubería fabricada','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3132,'detfamilia'=>'Ensambles fabricados de material en barras','slug'=>Str::slug('Ensambles fabricados de material en barras','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3133,'detfamilia'=>'Ensambles estructurales fabricados','slug'=>Str::slug('Ensambles estructurales fabricados','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3134,'detfamilia'=>'Ensambles de lámina fabricado','slug'=>Str::slug('Ensambles de lámina fabricado','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3135,'detfamilia'=>'Ensambles de tubería fabricada','slug'=>Str::slug('Ensambles de tubería fabricada','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3136,'detfamilia'=>'Ensambles de placa fabricados','slug'=>Str::slug('Ensambles de placa fabricados','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3137,'detfamilia'=>'Refractarios','slug'=>Str::slug('Refractarios','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3138,'detfamilia'=>'Imanes y materiales magnéticos','slug'=>Str::slug('Imanes y materiales magnéticos','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3139,'detfamilia'=>'Maquinados','slug'=>Str::slug('Maquinados','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3140,'detfamilia'=>'Empaques','slug'=>Str::slug('Empaques','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3141,'detfamilia'=>'Sellos','slug'=>Str::slug('Sellos','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3142,'detfamilia'=>'Partes sinterizadas','slug'=>Str::slug('Partes sinterizadas','-'),'segmento_id'=>'31',]);
Familia::create(['id'=>3210,'detfamilia'=>'Circuitos impresos, circuitos integrados y micro ensamblajes','slug'=>Str::slug('Circuitos impresos, circuitos integrados y micro ensamblajes','-'),'segmento_id'=>'32',]);
Familia::create(['id'=>3211,'detfamilia'=>'Dispositivo semiconductor discreto','slug'=>Str::slug('Dispositivo semiconductor discreto','-'),'segmento_id'=>'32',]);
Familia::create(['id'=>3212,'detfamilia'=>'Componentes pasivos discretos','slug'=>Str::slug('Componentes pasivos discretos','-'),'segmento_id'=>'32',]);
Familia::create(['id'=>3213,'detfamilia'=>'Piezas de componentes y hardware electrónicos y accesorios','slug'=>Str::slug('Piezas de componentes y hardware electrónicos y accesorios','-'),'segmento_id'=>'32',]);
Familia::create(['id'=>3214,'detfamilia'=>'Dispositivos de tubo electrónico y accesorios','slug'=>Str::slug('Dispositivos de tubo electrónico y accesorios','-'),'segmento_id'=>'32',]);
Familia::create(['id'=>3215,'detfamilia'=>'Dispositivos y componentes y accesorios de control de automatización','slug'=>Str::slug('Dispositivos y componentes y accesorios de control de automatización','-'),'segmento_id'=>'32',]);
Familia::create(['id'=>3910,'detfamilia'=>'Lámparas y bombillas y componentes para lámparas','slug'=>Str::slug('Lámparas y bombillas y componentes para lámparas','-'),'segmento_id'=>'39',]);
Familia::create(['id'=>3911,'detfamilia'=>'Iluminación, artefactos y accesorios','slug'=>Str::slug('Iluminación, artefactos y accesorios','-'),'segmento_id'=>'39',]);
Familia::create(['id'=>3912,'detfamilia'=>'Equipos, suministros y componentes eléctricos','slug'=>Str::slug('Equipos, suministros y componentes eléctricos','-'),'segmento_id'=>'39',]);
Familia::create(['id'=>3913,'detfamilia'=>'Dispositivos y accesorios y suministros de manejo de cable eléctrico','slug'=>Str::slug('Dispositivos y accesorios y suministros de manejo de cable eléctrico','-'),'segmento_id'=>'39',]);
Familia::create(['id'=>4010,'detfamilia'=>'Calefacción, ventilación y circulación del aire','slug'=>Str::slug('Calefacción, ventilación y circulación del aire','-'),'segmento_id'=>'40',]);
Familia::create(['id'=>4014,'detfamilia'=>'Distribución de fluidos y gas','slug'=>Str::slug('Distribución de fluidos y gas','-'),'segmento_id'=>'40',]);
Familia::create(['id'=>4015,'detfamilia'=>'Bombas y compresores industriales','slug'=>Str::slug('Bombas y compresores industriales','-'),'segmento_id'=>'40',]);
Familia::create(['id'=>4016,'detfamilia'=>'Filtrado y purificación industrial','slug'=>Str::slug('Filtrado y purificación industrial','-'),'segmento_id'=>'40',]);
Familia::create(['id'=>4017,'detfamilia'=>'Instalaciones de tubos y entubamientos','slug'=>Str::slug('Instalaciones de tubos y entubamientos','-'),'segmento_id'=>'40',]);
Familia::create(['id'=>4018,'detfamilia'=>'Instalaciones de tubos y tuberías','slug'=>Str::slug('Instalaciones de tubos y tuberías','-'),'segmento_id'=>'40',]);
Familia::create(['id'=>4110,'detfamilia'=>'Equipo de laboratorio y científico','slug'=>Str::slug('Equipo de laboratorio y científico','-'),'segmento_id'=>'41',]);
Familia::create(['id'=>4111,'detfamilia'=>'Instrumentos de medida, observación y ensayo','slug'=>Str::slug('Instrumentos de medida, observación y ensayo','-'),'segmento_id'=>'41',]);
Familia::create(['id'=>4112,'detfamilia'=>'Suministros y accesorios de laboratorio','slug'=>Str::slug('Suministros y accesorios de laboratorio','-'),'segmento_id'=>'41',]);
Familia::create(['id'=>4212,'detfamilia'=>'Equipos y suministros veterinarios','slug'=>Str::slug('Equipos y suministros veterinarios','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4213,'detfamilia'=>'Telas y vestidos médicos','slug'=>Str::slug('Telas y vestidos médicos','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4214,'detfamilia'=>'Suministros, productos de tratamiento y cuidado del enfermo','slug'=>Str::slug('Suministros, productos de tratamiento y cuidado del enfermo','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4215,'detfamilia'=>'Equipos y suministros dentales','slug'=>Str::slug('Equipos y suministros dentales','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4216,'detfamilia'=>'Equipo de diálisis y suministros','slug'=>Str::slug('Equipo de diálisis y suministros','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4217,'detfamilia'=>'Productos para los servicios médicos de urgencias y campo','slug'=>Str::slug('Productos para los servicios médicos de urgencias y campo','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4218,'detfamilia'=>'Productos de examen y control del paciente','slug'=>Str::slug('Productos de examen y control del paciente','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4219,'detfamilia'=>'Productos de centro médico','slug'=>Str::slug('Productos de centro médico','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4220,'detfamilia'=>'Productos de hacer imágenes diagnósticas médicas y de medicina nuclear','slug'=>Str::slug('Productos de hacer imágenes diagnósticas médicas y de medicina nuclear','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4221,'detfamilia'=>'Ayuda para personas con desafíos físicos para vivir independiente','slug'=>Str::slug('Ayuda para personas con desafíos físicos para vivir independiente','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4222,'detfamilia'=>'Productos para administración intravenosa y arterial','slug'=>Str::slug('Productos para administración intravenosa y arterial','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4223,'detfamilia'=>'Nutrición clínica','slug'=>Str::slug('Nutrición clínica','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4224,'detfamilia'=>'Productos medicinales de deportes y ortopédicos y prótesis','slug'=>Str::slug('Productos medicinales de deportes y ortopédicos y prótesis','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4225,'detfamilia'=>'Productos de rehabilitación y terapia ocupacional y física','slug'=>Str::slug('Productos de rehabilitación y terapia ocupacional y física','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4226,'detfamilia'=>'Equipo y suministros post mortem y funerarios','slug'=>Str::slug('Equipo y suministros post mortem y funerarios','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4227,'detfamilia'=>'Productos de resucitación, anestesia y respiratorio','slug'=>Str::slug('Productos de resucitación, anestesia y respiratorio','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4228,'detfamilia'=>'Productos para la esterilización médica','slug'=>Str::slug('Productos para la esterilización médica','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4229,'detfamilia'=>'Productos quirúrgicos','slug'=>Str::slug('Productos quirúrgicos','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4230,'detfamilia'=>'Suministros para formación y estudios de medicina','slug'=>Str::slug('Suministros para formación y estudios de medicina','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4231,'detfamilia'=>'Productos para el cuidado de heridas','slug'=>Str::slug('Productos para el cuidado de heridas','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4232,'detfamilia'=>'Implantes ortopédicos quirúrgicos','slug'=>Str::slug('Implantes ortopédicos quirúrgicos','-'),'segmento_id'=>'42',]);
Familia::create(['id'=>4319,'detfamilia'=>'Dispositivos de comunicaciones y accesorios','slug'=>Str::slug('Dispositivos de comunicaciones y accesorios','-'),'segmento_id'=>'43',]);
Familia::create(['id'=>4320,'detfamilia'=>'Componentes para tecnología de la información, difusión o telecomunicaciones','slug'=>Str::slug('Componentes para tecnología de la información, difusión o telecomunicaciones','-'),'segmento_id'=>'43',]);
Familia::create(['id'=>4321,'detfamilia'=>'Equipo informático y accesorios','slug'=>Str::slug('Equipo informático y accesorios','-'),'segmento_id'=>'43',]);
Familia::create(['id'=>4322,'detfamilia'=>'Equipos o plataformas y accesorios de redes multimedia o de voz y datos','slug'=>Str::slug('Equipos o plataformas y accesorios de redes multimedia o de voz y datos','-'),'segmento_id'=>'43',]);
Familia::create(['id'=>4323,'detfamilia'=>'Software','slug'=>Str::slug('Software','-'),'segmento_id'=>'43',]);
Familia::create(['id'=>4410,'detfamilia'=>'Maquinaria, suministros y accesorios de oficina','slug'=>Str::slug('Maquinaria, suministros y accesorios de oficina','-'),'segmento_id'=>'44',]);
Familia::create(['id'=>4411,'detfamilia'=>'Accesorios de oficina y escritorio','slug'=>Str::slug('Accesorios de oficina y escritorio','-'),'segmento_id'=>'44',]);
Familia::create(['id'=>4412,'detfamilia'=>'Suministros de oficina','slug'=>Str::slug('Suministros de oficina','-'),'segmento_id'=>'44',]);
Familia::create(['id'=>4510,'detfamilia'=>'Equipo de imprenta y publicación','slug'=>Str::slug('Equipo de imprenta y publicación','-'),'segmento_id'=>'45',]);
Familia::create(['id'=>4511,'detfamilia'=>'Equipos de audio y video para presentación y composición','slug'=>Str::slug('Equipos de audio y video para presentación y composición','-'),'segmento_id'=>'45',]);
Familia::create(['id'=>4512,'detfamilia'=>'Equipo de vídeo, filmación o fotografía','slug'=>Str::slug('Equipo de vídeo, filmación o fotografía','-'),'segmento_id'=>'45',]);
Familia::create(['id'=>4513,'detfamilia'=>'Medios fotográficos y de grabación','slug'=>Str::slug('Medios fotográficos y de grabación','-'),'segmento_id'=>'45',]);
Familia::create(['id'=>4514,'detfamilia'=>'Suministros fotográficos para cine','slug'=>Str::slug('Suministros fotográficos para cine','-'),'segmento_id'=>'45',]);
Familia::create(['id'=>4610,'detfamilia'=>'Armas ligeras y munición','slug'=>Str::slug('Armas ligeras y munición','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4611,'detfamilia'=>'Armas de guerra convencionales','slug'=>Str::slug('Armas de guerra convencionales','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4612,'detfamilia'=>'Misiles','slug'=>Str::slug('Misiles','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4613,'detfamilia'=>'Cohetes y subsistemas','slug'=>Str::slug('Cohetes y subsistemas','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4614,'detfamilia'=>'Lanzadores','slug'=>Str::slug('Lanzadores','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4615,'detfamilia'=>'Protección del Orden Público','slug'=>Str::slug('Protección del Orden Público','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4616,'detfamilia'=>'Seguridad y control público','slug'=>Str::slug('Seguridad y control público','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4617,'detfamilia'=>'Seguridad, vigilancia y detección','slug'=>Str::slug('Seguridad, vigilancia y detección','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4618,'detfamilia'=>'Seguridad y protección personal','slug'=>Str::slug('Seguridad y protección personal','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4619,'detfamilia'=>'Protección contra incendios','slug'=>Str::slug('Protección contra incendios','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4620,'detfamilia'=>'Equipo de entrenamiento de seguridad física e industrial, defensa y orden público','slug'=>Str::slug('Equipo de entrenamiento de seguridad física e industrial, defensa y orden público','-'),'segmento_id'=>'46',]);
Familia::create(['id'=>4710,'detfamilia'=>'Tratamiento, suministros y eliminación de agua y aguas residuales','slug'=>Str::slug('Tratamiento, suministros y eliminación de agua y aguas residuales','-'),'segmento_id'=>'47',]);
Familia::create(['id'=>4711,'detfamilia'=>'Equipo industrial de lavandería y lavado en seco','slug'=>Str::slug('Equipo industrial de lavandería y lavado en seco','-'),'segmento_id'=>'47',]);
Familia::create(['id'=>4712,'detfamilia'=>'Equipo de aseo','slug'=>Str::slug('Equipo de aseo','-'),'segmento_id'=>'47',]);
Familia::create(['id'=>4713,'detfamilia'=>'Suministros de aseo y limpieza','slug'=>Str::slug('Suministros de aseo y limpieza','-'),'segmento_id'=>'47',]);
Familia::create(['id'=>4810,'detfamilia'=>'Equipos de servicios de alimentación para instituciones','slug'=>Str::slug('Equipos de servicios de alimentación para instituciones','-'),'segmento_id'=>'48',]);
Familia::create(['id'=>4811,'detfamilia'=>'Máquinas expendedoras','slug'=>Str::slug('Máquinas expendedoras','-'),'segmento_id'=>'48',]);
Familia::create(['id'=>4812,'detfamilia'=>'Equipo de Juego o de Apostar','slug'=>Str::slug('Equipo de Juego o de Apostar','-'),'segmento_id'=>'48',]);
Familia::create(['id'=>4813,'detfamilia'=>'Equipo y materiales funerarios','slug'=>Str::slug('Equipo y materiales funerarios','-'),'segmento_id'=>'48',]);
Familia::create(['id'=>4910,'detfamilia'=>'Coleccionables y condecoraciones','slug'=>Str::slug('Coleccionables y condecoraciones','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4912,'detfamilia'=>'Equipos y accesorios para acampada y exteriores','slug'=>Str::slug('Equipos y accesorios para acampada y exteriores','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4913,'detfamilia'=>'Equipos de pesca y caza','slug'=>Str::slug('Equipos de pesca y caza','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4914,'detfamilia'=>'Equipos para deportes acuáticos','slug'=>Str::slug('Equipos para deportes acuáticos','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4915,'detfamilia'=>'Equipos para deportes de invierno','slug'=>Str::slug('Equipos para deportes de invierno','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4916,'detfamilia'=>'Equipos deportivos para campos y canchas','slug'=>Str::slug('Equipos deportivos para campos y canchas','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4917,'detfamilia'=>'Equipos de gimnasia y boxeo','slug'=>Str::slug('Equipos de gimnasia y boxeo','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4918,'detfamilia'=>'Juegos, equipo de tiro y mesa','slug'=>Str::slug('Juegos, equipo de tiro y mesa','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4920,'detfamilia'=>'Equipo para entrenamiento físico','slug'=>Str::slug('Equipo para entrenamiento físico','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4921,'detfamilia'=>'Otros deportes','slug'=>Str::slug('Otros deportes','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4922,'detfamilia'=>'Equipo  y accesorios para deportes','slug'=>Str::slug('Equipo  y accesorios para deportes','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>4924,'detfamilia'=>'Equipo de recreo, parques infantiles y equipo y suministros de natación y de spa','slug'=>Str::slug('Equipo de recreo, parques infantiles y equipo y suministros de natación y de spa','-'),'segmento_id'=>'49',]);
Familia::create(['id'=>5010,'detfamilia'=>'Frutos secos','slug'=>Str::slug('Frutos secos','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5011,'detfamilia'=>'Productos de carne y aves de corral','slug'=>Str::slug('Productos de carne y aves de corral','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5012,'detfamilia'=>'Pescados y mariscos','slug'=>Str::slug('Pescados y mariscos','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5013,'detfamilia'=>'Productos lácteos y huevos','slug'=>Str::slug('Productos lácteos y huevos','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5015,'detfamilia'=>'Aceites y grasas comestibles','slug'=>Str::slug('Aceites y grasas comestibles','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5016,'detfamilia'=>'Chocolates, azúcares, edulcorantes y productos de confitería','slug'=>Str::slug('Chocolates, azúcares, edulcorantes y productos de confitería','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5017,'detfamilia'=>'Condimentos y conservantes','slug'=>Str::slug('Condimentos y conservantes','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5018,'detfamilia'=>'Productos de panadería','slug'=>Str::slug('Productos de panadería','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5019,'detfamilia'=>'Alimentos preparados y conservados','slug'=>Str::slug('Alimentos preparados y conservados','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5020,'detfamilia'=>'Bebidas','slug'=>Str::slug('Bebidas','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5021,'detfamilia'=>'Tabaco y productos de fumar y substitutos','slug'=>Str::slug('Tabaco y productos de fumar y substitutos','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5022,'detfamilia'=>'Productos de cereales y legumbres','slug'=>Str::slug('Productos de cereales y legumbres','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5030,'detfamilia'=>'Fruta fresca','slug'=>Str::slug('Fruta fresca','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5031,'detfamilia'=>'Fruta orgánica fresca','slug'=>Str::slug('Fruta orgánica fresca','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5032,'detfamilia'=>'Fruta seca','slug'=>Str::slug('Fruta seca','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5033,'detfamilia'=>'Fruta orgánica seca','slug'=>Str::slug('Fruta orgánica seca','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5034,'detfamilia'=>'Fruta congelada','slug'=>Str::slug('Fruta congelada','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5035,'detfamilia'=>'Fruta orgánica congelada','slug'=>Str::slug('Fruta orgánica congelada','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5036,'detfamilia'=>'Fruta en lata o en frasco','slug'=>Str::slug('Fruta en lata o en frasco','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5037,'detfamilia'=>'Fruta orgánica en lata o en frasco','slug'=>Str::slug('Fruta orgánica en lata o en frasco','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5038,'detfamilia'=>'Puré de frutas','slug'=>Str::slug('Puré de frutas','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5040,'detfamilia'=>'Vegetales frescos','slug'=>Str::slug('Vegetales frescos','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5041,'detfamilia'=>'Vegetales orgánicos frescos','slug'=>Str::slug('Vegetales orgánicos frescos','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5042,'detfamilia'=>'Vegetales secos','slug'=>Str::slug('Vegetales secos','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5043,'detfamilia'=>'Vegetales orgánicos secos','slug'=>Str::slug('Vegetales orgánicos secos','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5044,'detfamilia'=>'Vegetales congelados','slug'=>Str::slug('Vegetales congelados','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5045,'detfamilia'=>'Vegetales orgánicos congelados','slug'=>Str::slug('Vegetales orgánicos congelados','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5046,'detfamilia'=>'Vegetales en lata o en frasco','slug'=>Str::slug('Vegetales en lata o en frasco','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5047,'detfamilia'=>'Vegetales orgánicos en lata o en frasco','slug'=>Str::slug('Vegetales orgánicos en lata o en frasco','-'),'segmento_id'=>'50',]);
Familia::create(['id'=>5110,'detfamilia'=>'Medicamentos antiinfecciosos','slug'=>Str::slug('Medicamentos antiinfecciosos','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5111,'detfamilia'=>'Agentes antitumorales','slug'=>Str::slug('Agentes antitumorales','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5112,'detfamilia'=>'Medicamentos cardiovasculares','slug'=>Str::slug('Medicamentos cardiovasculares','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5113,'detfamilia'=>'Medicamentos hematólogos','slug'=>Str::slug('Medicamentos hematólogos','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5114,'detfamilia'=>'Medicamentos para el sistema nervioso central','slug'=>Str::slug('Medicamentos para el sistema nervioso central','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5115,'detfamilia'=>'Medicamentos para el sistema nervioso autónomo','slug'=>Str::slug('Medicamentos para el sistema nervioso autónomo','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5116,'detfamilia'=>'Medicamentos que afectan al sistema respiratorio','slug'=>Str::slug('Medicamentos que afectan al sistema respiratorio','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5117,'detfamilia'=>'Medicamentos que afectan al sistema gastrointestinal','slug'=>Str::slug('Medicamentos que afectan al sistema gastrointestinal','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5118,'detfamilia'=>'Hormonas y antagonistas hormonales','slug'=>Str::slug('Hormonas y antagonistas hormonales','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5119,'detfamilia'=>'Agentes que afectan el agua y los electrolitos','slug'=>Str::slug('Agentes que afectan el agua y los electrolitos','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5120,'detfamilia'=>'Medicamentos inmunomoduladores','slug'=>Str::slug('Medicamentos inmunomoduladores','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5121,'detfamilia'=>'Categorías de medicamentos varios','slug'=>Str::slug('Categorías de medicamentos varios','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5124,'detfamilia'=>'Fármacos que afectan a los oídos, los ojos, la nariz y la piel','slug'=>Str::slug('Fármacos que afectan a los oídos, los ojos, la nariz y la piel','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5125,'detfamilia'=>'Suplementos alimenticios veterinarios','slug'=>Str::slug('Suplementos alimenticios veterinarios','-'),'segmento_id'=>'51',]);
Familia::create(['id'=>5210,'detfamilia'=>'Revestimientos de suelos','slug'=>Str::slug('Revestimientos de suelos','-'),'segmento_id'=>'52',]);
Familia::create(['id'=>5212,'detfamilia'=>'Ropa de cama, mantelerías, paños de cocina y toallas','slug'=>Str::slug('Ropa de cama, mantelerías, paños de cocina y toallas','-'),'segmento_id'=>'52',]);
Familia::create(['id'=>5213,'detfamilia'=>'Tratamientos de ventanas','slug'=>Str::slug('Tratamientos de ventanas','-'),'segmento_id'=>'52',]);
Familia::create(['id'=>5214,'detfamilia'=>'Aparatos electrodomésticos','slug'=>Str::slug('Aparatos electrodomésticos','-'),'segmento_id'=>'52',]);
Familia::create(['id'=>5215,'detfamilia'=>'Utensilios de cocina domésticos','slug'=>Str::slug('Utensilios de cocina domésticos','-'),'segmento_id'=>'52',]);
Familia::create(['id'=>5216,'detfamilia'=>'Electrónica de consumo','slug'=>Str::slug('Electrónica de consumo','-'),'segmento_id'=>'52',]);
Familia::create(['id'=>5217,'detfamilia'=>'Tratamientos de pared doméstica','slug'=>Str::slug('Tratamientos de pared doméstica','-'),'segmento_id'=>'52',]);
Familia::create(['id'=>5310,'detfamilia'=>'Ropa','slug'=>Str::slug('Ropa','-'),'segmento_id'=>'53',]);
Familia::create(['id'=>5311,'detfamilia'=>'Calzado','slug'=>Str::slug('Calzado','-'),'segmento_id'=>'53',]);
Familia::create(['id'=>5312,'detfamilia'=>'Maletas, bolsos de mano, mochilas y estuches','slug'=>Str::slug('Maletas, bolsos de mano, mochilas y estuches','-'),'segmento_id'=>'53',]);
Familia::create(['id'=>5313,'detfamilia'=>'Artículos de tocador y cuidado personal','slug'=>Str::slug('Artículos de tocador y cuidado personal','-'),'segmento_id'=>'53',]);
Familia::create(['id'=>5314,'detfamilia'=>'Fuentes y accesorios de costura','slug'=>Str::slug('Fuentes y accesorios de costura','-'),'segmento_id'=>'53',]);
Familia::create(['id'=>5410,'detfamilia'=>'Joyería','slug'=>Str::slug('Joyería','-'),'segmento_id'=>'54',]);
Familia::create(['id'=>5411,'detfamilia'=>'Relojes','slug'=>Str::slug('Relojes','-'),'segmento_id'=>'54',]);
Familia::create(['id'=>5412,'detfamilia'=>'Gemas','slug'=>Str::slug('Gemas','-'),'segmento_id'=>'54',]);
Familia::create(['id'=>5510,'detfamilia'=>'Medios impresos','slug'=>Str::slug('Medios impresos','-'),'segmento_id'=>'55',]);
Familia::create(['id'=>5511,'detfamilia'=>'Material electrónico de referencia','slug'=>Str::slug('Material electrónico de referencia','-'),'segmento_id'=>'55',]);
Familia::create(['id'=>5512,'detfamilia'=>'Etiquetado y accesorios','slug'=>Str::slug('Etiquetado y accesorios','-'),'segmento_id'=>'55',]);
Familia::create(['id'=>5610,'detfamilia'=>'Muebles de alojamiento','slug'=>Str::slug('Muebles de alojamiento','-'),'segmento_id'=>'56',]);
Familia::create(['id'=>5611,'detfamilia'=>'Muebles comerciales e industriales','slug'=>Str::slug('Muebles comerciales e industriales','-'),'segmento_id'=>'56',]);
Familia::create(['id'=>5612,'detfamilia'=>'Mobiliario institucional, escolar y educativo y accesorios','slug'=>Str::slug('Mobiliario institucional, escolar y educativo y accesorios','-'),'segmento_id'=>'56',]);
Familia::create(['id'=>5613,'detfamilia'=>'Muebles y accesorios para merchandising','slug'=>Str::slug('Muebles y accesorios para merchandising','-'),'segmento_id'=>'56',]);
Familia::create(['id'=>5614,'detfamilia'=>'Adornos para el hogar','slug'=>Str::slug('Adornos para el hogar','-'),'segmento_id'=>'56',]);
Familia::create(['id'=>6010,'detfamilia'=>'Materiales didácticos profesionales y de desarrollo y accesorios y suministros','slug'=>Str::slug('Materiales didácticos profesionales y de desarrollo y accesorios y suministros','-'),'segmento_id'=>'60',]);
Familia::create(['id'=>6011,'detfamilia'=>'Decoraciones y suministros del aula','slug'=>Str::slug('Decoraciones y suministros del aula','-'),'segmento_id'=>'60',]);
Familia::create(['id'=>6012,'detfamilia'=>'Equipo, accesorios y suministros de arte y manualidades','slug'=>Str::slug('Equipo, accesorios y suministros de arte y manualidades','-'),'segmento_id'=>'60',]);
Familia::create(['id'=>6013,'detfamilia'=>'Instrumentos musicales, piezas y accesorios','slug'=>Str::slug('Instrumentos musicales, piezas y accesorios','-'),'segmento_id'=>'60',]);
Familia::create(['id'=>6014,'detfamilia'=>'Juguetes y juegos','slug'=>Str::slug('Juguetes y juegos','-'),'segmento_id'=>'60',]);
Familia::create(['id'=>7010,'detfamilia'=>'Pesquerías y acuicultura','slug'=>Str::slug('Pesquerías y acuicultura','-'),'segmento_id'=>'70',]);
Familia::create(['id'=>7011,'detfamilia'=>'Horticultura','slug'=>Str::slug('Horticultura','-'),'segmento_id'=>'70',]);
Familia::create(['id'=>7012,'detfamilia'=>'Servicios de animales vivos','slug'=>Str::slug('Servicios de animales vivos','-'),'segmento_id'=>'70',]);
Familia::create(['id'=>7013,'detfamilia'=>'Preparación, gestión y protección del terreno y del suelo','slug'=>Str::slug('Preparación, gestión y protección del terreno y del suelo','-'),'segmento_id'=>'70',]);
Familia::create(['id'=>7014,'detfamilia'=>'Producción, gestión y protección de cultivos','slug'=>Str::slug('Producción, gestión y protección de cultivos','-'),'segmento_id'=>'70',]);
Familia::create(['id'=>7015,'detfamilia'=>'Silvicultura','slug'=>Str::slug('Silvicultura','-'),'segmento_id'=>'70',]);
Familia::create(['id'=>7016,'detfamilia'=>'Fauna y flora silvestres','slug'=>Str::slug('Fauna y flora silvestres','-'),'segmento_id'=>'70',]);
Familia::create(['id'=>7017,'detfamilia'=>'Desarrollo y vigilancia de recursos hidráulicos','slug'=>Str::slug('Desarrollo y vigilancia de recursos hidráulicos','-'),'segmento_id'=>'70',]);
Familia::create(['id'=>7110,'detfamilia'=>'Servicios de minería','slug'=>Str::slug('Servicios de minería','-'),'segmento_id'=>'71',]);
Familia::create(['id'=>7111,'detfamilia'=>'Servicios de perforación y prospección petrolífera y de gas','slug'=>Str::slug('Servicios de perforación y prospección petrolífera y de gas','-'),'segmento_id'=>'71',]);
Familia::create(['id'=>7112,'detfamilia'=>'Servicios de construcción y perforación de pozos','slug'=>Str::slug('Servicios de construcción y perforación de pozos','-'),'segmento_id'=>'71',]);
Familia::create(['id'=>7113,'detfamilia'=>'Servicios de aumento de la extracción y producción de gas y petróleo','slug'=>Str::slug('Servicios de aumento de la extracción y producción de gas y petróleo','-'),'segmento_id'=>'71',]);
Familia::create(['id'=>7114,'detfamilia'=>'Servicios de restauración y recuperación de gas y petróleo','slug'=>Str::slug('Servicios de restauración y recuperación de gas y petróleo','-'),'segmento_id'=>'71',]);
Familia::create(['id'=>7115,'detfamilia'=>'Servicios de procesamiento y gestión de datos de petróleo y gas','slug'=>Str::slug('Servicios de procesamiento y gestión de datos de petróleo y gas','-'),'segmento_id'=>'71',]);
Familia::create(['id'=>7116,'detfamilia'=>'Servicios de gerencia de proyectos en pozos de petróleo y gas','slug'=>Str::slug('Servicios de gerencia de proyectos en pozos de petróleo y gas','-'),'segmento_id'=>'71',]);
Familia::create(['id'=>7210,'detfamilia'=>'Servicios de mantenimiento y reparaciones de construcciones e instalaciones','slug'=>Str::slug('Servicios de mantenimiento y reparaciones de construcciones e instalaciones','-'),'segmento_id'=>'72',]);
Familia::create(['id'=>7211,'detfamilia'=>'Servicios de construcción de edificaciones residenciales','slug'=>Str::slug('Servicios de construcción de edificaciones residenciales','-'),'segmento_id'=>'72',]);
Familia::create(['id'=>7212,'detfamilia'=>'Servicios de construcción de edificaciones no residenciales','slug'=>Str::slug('Servicios de construcción de edificaciones no residenciales','-'),'segmento_id'=>'72',]);
Familia::create(['id'=>7214,'detfamilia'=>'Servicios de construcción pesada','slug'=>Str::slug('Servicios de construcción pesada','-'),'segmento_id'=>'72',]);
Familia::create(['id'=>7215,'detfamilia'=>'Servicios de mantenimiento y construcción de comercio especializado','slug'=>Str::slug('Servicios de mantenimiento y construcción de comercio especializado','-'),'segmento_id'=>'72',]);
Familia::create(['id'=>7310,'detfamilia'=>'Industrias de plásticos y productos químicos','slug'=>Str::slug('Industrias de plásticos y productos químicos','-'),'segmento_id'=>'73',]);
Familia::create(['id'=>7311,'detfamilia'=>'Industrias de la madera y el papel','slug'=>Str::slug('Industrias de la madera y el papel','-'),'segmento_id'=>'73',]);
Familia::create(['id'=>7312,'detfamilia'=>'Industrias del metal y de minerales','slug'=>Str::slug('Industrias del metal y de minerales','-'),'segmento_id'=>'73',]);
Familia::create(['id'=>7313,'detfamilia'=>'Industrias de alimentos y bebidas','slug'=>Str::slug('Industrias de alimentos y bebidas','-'),'segmento_id'=>'73',]);
Familia::create(['id'=>7314,'detfamilia'=>'Industrias de fibras, textiles y de tejidos','slug'=>Str::slug('Industrias de fibras, textiles y de tejidos','-'),'segmento_id'=>'73',]);
Familia::create(['id'=>7315,'detfamilia'=>'Servicios de apoyo a la fabricación','slug'=>Str::slug('Servicios de apoyo a la fabricación','-'),'segmento_id'=>'73',]);
Familia::create(['id'=>7316,'detfamilia'=>'Fabricación de maquinaria y equipo de transporte','slug'=>Str::slug('Fabricación de maquinaria y equipo de transporte','-'),'segmento_id'=>'73',]);
Familia::create(['id'=>7317,'detfamilia'=>'Fabricación de productos eléctricos e instrumentos de precisión','slug'=>Str::slug('Fabricación de productos eléctricos e instrumentos de precisión','-'),'segmento_id'=>'73',]);
Familia::create(['id'=>7318,'detfamilia'=>'Servicios de maquinado y procesado','slug'=>Str::slug('Servicios de maquinado y procesado','-'),'segmento_id'=>'73',]);
Familia::create(['id'=>7610,'detfamilia'=>'Servicios de descontaminación','slug'=>Str::slug('Servicios de descontaminación','-'),'segmento_id'=>'76',]);
Familia::create(['id'=>7611,'detfamilia'=>'Servicios de aseo y limpieza','slug'=>Str::slug('Servicios de aseo y limpieza','-'),'segmento_id'=>'76',]);
Familia::create(['id'=>7612,'detfamilia'=>'Eliminación y tratamiento de desechos','slug'=>Str::slug('Eliminación y tratamiento de desechos','-'),'segmento_id'=>'76',]);
Familia::create(['id'=>7613,'detfamilia'=>'Limpieza de residuos tóxicos y peligrosos','slug'=>Str::slug('Limpieza de residuos tóxicos y peligrosos','-'),'segmento_id'=>'76',]);
Familia::create(['id'=>7710,'detfamilia'=>'Gestión medioambiental','slug'=>Str::slug('Gestión medioambiental','-'),'segmento_id'=>'77',]);
Familia::create(['id'=>7711,'detfamilia'=>'Protección medioambiental','slug'=>Str::slug('Protección medioambiental','-'),'segmento_id'=>'77',]);
Familia::create(['id'=>7712,'detfamilia'=>'Seguimiento, control y rehabilitación de la contaminación','slug'=>Str::slug('Seguimiento, control y rehabilitación de la contaminación','-'),'segmento_id'=>'77',]);
Familia::create(['id'=>7713,'detfamilia'=>'Servicios de seguimiento, control o rehabilitación de contaminantes','slug'=>Str::slug('Servicios de seguimiento, control o rehabilitación de contaminantes','-'),'segmento_id'=>'77',]);
Familia::create(['id'=>7810,'detfamilia'=>'Transporte de correo y carga','slug'=>Str::slug('Transporte de correo y carga','-'),'segmento_id'=>'78',]);
Familia::create(['id'=>7811,'detfamilia'=>'Transporte de pasajeros','slug'=>Str::slug('Transporte de pasajeros','-'),'segmento_id'=>'78',]);
Familia::create(['id'=>7812,'detfamilia'=>'Manejo y embalaje de material','slug'=>Str::slug('Manejo y embalaje de material','-'),'segmento_id'=>'78',]);
Familia::create(['id'=>7813,'detfamilia'=>'Almacenaje','slug'=>Str::slug('Almacenaje','-'),'segmento_id'=>'78',]);
Familia::create(['id'=>7814,'detfamilia'=>'Servicios de transporte','slug'=>Str::slug('Servicios de transporte','-'),'segmento_id'=>'78',]);
Familia::create(['id'=>7818,'detfamilia'=>'Servicios de mantenimiento o reparaciones de transportes','slug'=>Str::slug('Servicios de mantenimiento o reparaciones de transportes','-'),'segmento_id'=>'78',]);
Familia::create(['id'=>8010,'detfamilia'=>'Servicios de asesoría de gestión','slug'=>Str::slug('Servicios de asesoría de gestión','-'),'segmento_id'=>'80',]);
Familia::create(['id'=>8011,'detfamilia'=>'Servicios de recursos humanos','slug'=>Str::slug('Servicios de recursos humanos','-'),'segmento_id'=>'80',]);
Familia::create(['id'=>8012,'detfamilia'=>'Servicios legales','slug'=>Str::slug('Servicios legales','-'),'segmento_id'=>'80',]);
Familia::create(['id'=>8013,'detfamilia'=>'Servicios inmobiliarios','slug'=>Str::slug('Servicios inmobiliarios','-'),'segmento_id'=>'80',]);
Familia::create(['id'=>8014,'detfamilia'=>'Comercialización y distribución','slug'=>Str::slug('Comercialización y distribución','-'),'segmento_id'=>'80',]);
Familia::create(['id'=>8015,'detfamilia'=>'Política comercial y servicios','slug'=>Str::slug('Política comercial y servicios','-'),'segmento_id'=>'80',]);
Familia::create(['id'=>8016,'detfamilia'=>'Servicios de administración de empresas','slug'=>Str::slug('Servicios de administración de empresas','-'),'segmento_id'=>'80',]);
Familia::create(['id'=>8110,'detfamilia'=>'Servicios profesionales de ingeniería','slug'=>Str::slug('Servicios profesionales de ingeniería','-'),'segmento_id'=>'81',]);
Familia::create(['id'=>8111,'detfamilia'=>'Servicios informáticos','slug'=>Str::slug('Servicios informáticos','-'),'segmento_id'=>'81',]);
Familia::create(['id'=>8112,'detfamilia'=>'Economía','slug'=>Str::slug('Economía','-'),'segmento_id'=>'81',]);
Familia::create(['id'=>8113,'detfamilia'=>'Estadística','slug'=>Str::slug('Estadística','-'),'segmento_id'=>'81',]);
Familia::create(['id'=>8114,'detfamilia'=>'Tecnologías de fabricación','slug'=>Str::slug('Tecnologías de fabricación','-'),'segmento_id'=>'81',]);
Familia::create(['id'=>8115,'detfamilia'=>'Servicios de pedología','slug'=>Str::slug('Servicios de pedología','-'),'segmento_id'=>'81',]);
Familia::create(['id'=>8116,'detfamilia'=>'Entrega de servicios de tecnología de información','slug'=>Str::slug('Entrega de servicios de tecnología de información','-'),'segmento_id'=>'81',]);
Familia::create(['id'=>8210,'detfamilia'=>'Publicidad','slug'=>Str::slug('Publicidad','-'),'segmento_id'=>'82',]);
Familia::create(['id'=>8211,'detfamilia'=>'Escritura y traducciones','slug'=>Str::slug('Escritura y traducciones','-'),'segmento_id'=>'82',]);
Familia::create(['id'=>8212,'detfamilia'=>'Servicios de reproducción','slug'=>Str::slug('Servicios de reproducción','-'),'segmento_id'=>'82',]);
Familia::create(['id'=>8213,'detfamilia'=>'Servicios fotográficos','slug'=>Str::slug('Servicios fotográficos','-'),'segmento_id'=>'82',]);
Familia::create(['id'=>8214,'detfamilia'=>'Diseño gráfico','slug'=>Str::slug('Diseño gráfico','-'),'segmento_id'=>'82',]);
Familia::create(['id'=>8215,'detfamilia'=>'Artistas e intérpretes profesionales','slug'=>Str::slug('Artistas e intérpretes profesionales','-'),'segmento_id'=>'82',]);
Familia::create(['id'=>8310,'detfamilia'=>'Servicios públicos','slug'=>Str::slug('Servicios públicos','-'),'segmento_id'=>'83',]);
Familia::create(['id'=>8311,'detfamilia'=>'Servicios de medios de telecomunicaciones','slug'=>Str::slug('Servicios de medios de telecomunicaciones','-'),'segmento_id'=>'83',]);
Familia::create(['id'=>8312,'detfamilia'=>'Servicios de información','slug'=>Str::slug('Servicios de información','-'),'segmento_id'=>'83',]);
Familia::create(['id'=>8410,'detfamilia'=>'Finanzas de desarrollo','slug'=>Str::slug('Finanzas de desarrollo','-'),'segmento_id'=>'84',]);
Familia::create(['id'=>8411,'detfamilia'=>'Servicios de contabilidad y auditorias','slug'=>Str::slug('Servicios de contabilidad y auditorias','-'),'segmento_id'=>'84',]);
Familia::create(['id'=>8412,'detfamilia'=>'Banca e inversiones','slug'=>Str::slug('Banca e inversiones','-'),'segmento_id'=>'84',]);
Familia::create(['id'=>8413,'detfamilia'=>'Servicios de seguros y pensiones','slug'=>Str::slug('Servicios de seguros y pensiones','-'),'segmento_id'=>'84',]);
Familia::create(['id'=>8414,'detfamilia'=>'Agencias de crédito','slug'=>Str::slug('Agencias de crédito','-'),'segmento_id'=>'84',]);
Familia::create(['id'=>8510,'detfamilia'=>'Servicios integrales de salud','slug'=>Str::slug('Servicios integrales de salud','-'),'segmento_id'=>'85',]);
Familia::create(['id'=>8511,'detfamilia'=>'Prevención y control de enfermedades','slug'=>Str::slug('Prevención y control de enfermedades','-'),'segmento_id'=>'85',]);
Familia::create(['id'=>8512,'detfamilia'=>'Práctica médica','slug'=>Str::slug('Práctica médica','-'),'segmento_id'=>'85',]);
Familia::create(['id'=>8513,'detfamilia'=>'Ciencia médica, investigación y experimentación','slug'=>Str::slug('Ciencia médica, investigación y experimentación','-'),'segmento_id'=>'85',]);
Familia::create(['id'=>8514,'detfamilia'=>'Medicina alternativa y holística','slug'=>Str::slug('Medicina alternativa y holística','-'),'segmento_id'=>'85',]);
Familia::create(['id'=>8515,'detfamilia'=>'Servicios alimenticios y de nutrición','slug'=>Str::slug('Servicios alimenticios y de nutrición','-'),'segmento_id'=>'85',]);
Familia::create(['id'=>8516,'detfamilia'=>'Servicios de mantenimiento, renovación y reparación de equipo médico quirúrgico','slug'=>Str::slug('Servicios de mantenimiento, renovación y reparación de equipo médico quirúrgico','-'),'segmento_id'=>'85',]);
Familia::create(['id'=>8517,'detfamilia'=>'Servicios de muerte y soporte al fallecimiento','slug'=>Str::slug('Servicios de muerte y soporte al fallecimiento','-'),'segmento_id'=>'85',]);
Familia::create(['id'=>8610,'detfamilia'=>'Formación profesional','slug'=>Str::slug('Formación profesional','-'),'segmento_id'=>'86',]);
Familia::create(['id'=>8611,'detfamilia'=>'Sistemas educativos alternativos','slug'=>Str::slug('Sistemas educativos alternativos','-'),'segmento_id'=>'86',]);
Familia::create(['id'=>8612,'detfamilia'=>'Instituciones educativas','slug'=>Str::slug('Instituciones educativas','-'),'segmento_id'=>'86',]);
Familia::create(['id'=>8613,'detfamilia'=>'Servicios educativos especializados','slug'=>Str::slug('Servicios educativos especializados','-'),'segmento_id'=>'86',]);
Familia::create(['id'=>8614,'detfamilia'=>'Instalaciones educativas','slug'=>Str::slug('Instalaciones educativas','-'),'segmento_id'=>'86',]);
Familia::create(['id'=>9010,'detfamilia'=>'Restaurantes y catering (servicios de comidas y bebidas)','slug'=>Str::slug('Restaurantes y catering (servicios de comidas y bebidas)','-'),'segmento_id'=>'90',]);
Familia::create(['id'=>9011,'detfamilia'=>'Instalaciones hoteleras, alojamientos y centros de encuentros','slug'=>Str::slug('Instalaciones hoteleras, alojamientos y centros de encuentros','-'),'segmento_id'=>'90',]);
Familia::create(['id'=>9012,'detfamilia'=>'Facilitación de viajes','slug'=>Str::slug('Facilitación de viajes','-'),'segmento_id'=>'90',]);
Familia::create(['id'=>9013,'detfamilia'=>'Artes interpretativas','slug'=>Str::slug('Artes interpretativas','-'),'segmento_id'=>'90',]);
Familia::create(['id'=>9014,'detfamilia'=>'Deportes comerciales','slug'=>Str::slug('Deportes comerciales','-'),'segmento_id'=>'90',]);
Familia::create(['id'=>9015,'detfamilia'=>'Servicios de entretenimiento','slug'=>Str::slug('Servicios de entretenimiento','-'),'segmento_id'=>'90',]);
Familia::create(['id'=>9110,'detfamilia'=>'Aspecto personal','slug'=>Str::slug('Aspecto personal','-'),'segmento_id'=>'91',]);
Familia::create(['id'=>9111,'detfamilia'=>'Asistencia doméstica y personal','slug'=>Str::slug('Asistencia doméstica y personal','-'),'segmento_id'=>'91',]);
Familia::create(['id'=>9210,'detfamilia'=>'Orden público y seguridad','slug'=>Str::slug('Orden público y seguridad','-'),'segmento_id'=>'92',]);
Familia::create(['id'=>9211,'detfamilia'=>'Servicios militares o defensa nacional','slug'=>Str::slug('Servicios militares o defensa nacional','-'),'segmento_id'=>'92',]);
Familia::create(['id'=>9212,'detfamilia'=>'Seguridad y protección personal','slug'=>Str::slug('Seguridad y protección personal','-'),'segmento_id'=>'92',]);
Familia::create(['id'=>9310,'detfamilia'=>'Sistemas e instituciones políticas','slug'=>Str::slug('Sistemas e instituciones políticas','-'),'segmento_id'=>'93',]);
Familia::create(['id'=>9311,'detfamilia'=>'Condiciones sociopolíticas','slug'=>Str::slug('Condiciones sociopolíticas','-'),'segmento_id'=>'93',]);
Familia::create(['id'=>9312,'detfamilia'=>'Relaciones internacionales','slug'=>Str::slug('Relaciones internacionales','-'),'segmento_id'=>'93',]);
Familia::create(['id'=>9313,'detfamilia'=>'Ayuda y asistencia humanitaria','slug'=>Str::slug('Ayuda y asistencia humanitaria','-'),'segmento_id'=>'93',]);
Familia::create(['id'=>9314,'detfamilia'=>'Servicios comunitarios y sociales','slug'=>Str::slug('Servicios comunitarios y sociales','-'),'segmento_id'=>'93',]);
Familia::create(['id'=>9315,'detfamilia'=>'Servicios de administración y financiación pública','slug'=>Str::slug('Servicios de administración y financiación pública','-'),'segmento_id'=>'93',]);
Familia::create(['id'=>9316,'detfamilia'=>'Tributación','slug'=>Str::slug('Tributación','-'),'segmento_id'=>'93',]);
Familia::create(['id'=>9317,'detfamilia'=>'Política y regulación comercial','slug'=>Str::slug('Política y regulación comercial','-'),'segmento_id'=>'94',]);
Familia::create(['id'=>9410,'detfamilia'=>'Organizaciones laborales','slug'=>Str::slug('Organizaciones laborales','-'),'segmento_id'=>'94',]);
Familia::create(['id'=>9411,'detfamilia'=>'Organizaciones religiosas','slug'=>Str::slug('Organizaciones religiosas','-'),'segmento_id'=>'94',]);
Familia::create(['id'=>9412,'detfamilia'=>'Clubes','slug'=>Str::slug('Clubes','-'),'segmento_id'=>'94',]);
Familia::create(['id'=>9413,'detfamilia'=>'Organizaciones, asociaciones y movimientos cívicos','slug'=>Str::slug('Organizaciones, asociaciones y movimientos cívicos','-'),'segmento_id'=>'94',]);
Familia::create(['id'=>9510,'detfamilia'=>'Parcelas de tierra','slug'=>Str::slug('Parcelas de tierra','-'),'segmento_id'=>'95',]);
Familia::create(['id'=>9511,'detfamilia'=>'Vías','slug'=>Str::slug('Vías','-'),'segmento_id'=>'95',]);
Familia::create(['id'=>9512,'detfamilia'=>'Estructuras y edificios permanentes','slug'=>Str::slug('Estructuras y edificios permanentes','-'),'segmento_id'=>'95',]);
Familia::create(['id'=>9513,'detfamilia'=>'Estructuras y edificios móviles','slug'=>Str::slug('Estructuras y edificios móviles','-'),'segmento_id'=>'95',]);
Familia::create(['id'=>9514,'detfamilia'=>'Estructuras y edificios prefabricados','slug'=>Str::slug('Estructuras y edificios prefabricados','-'),'segmento_id'=>'95',]);
 
    }
}
